steps:
  # Step 1: Build Docker image from rust_orchestrator/Dockerfile
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - '${_AR_HOSTNAME}/${_AR_PROJECT_ID}/${_AR_REPOSITORY}/agent-samwise:latest'
      - '-t'
      - '${_AR_HOSTNAME}/${_AR_PROJECT_ID}/${_AR_REPOSITORY}/agent-samwise:$COMMIT_SHA'
      - '-f'
      - 'rust_orchestrator/Dockerfile'
      - 'rust_orchestrator/'
    id: 'build-image'

  # Step 2: Push to Artifact Registry (latest tag)
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - '${_AR_HOSTNAME}/${_AR_PROJECT_ID}/${_AR_REPOSITORY}/agent-samwise:latest'
    id: 'push-latest'

  # Step 3: Push to Artifact Registry (commit SHA tag)
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - '${_AR_HOSTNAME}/${_AR_PROJECT_ID}/${_AR_REPOSITORY}/agent-samwise:$COMMIT_SHA'
    id: 'push-commit'

  # Step 4: Deploy to Cloud Run
  - name: 'gcr.io/cloud-builders/run'
    args:
      - 'deploy'
      - '${_SERVICE_NAME}'
      - '--image'
      - '${_AR_HOSTNAME}/${_AR_PROJECT_ID}/${_AR_REPOSITORY}/agent-samwise:latest'
      - '--region'
      - '${_DEPLOY_REGION}'
      - '--platform'
      - '${_PLATFORM}'
      - '--allow-unauthenticated'
      - '--memory'
      - '1Gi'
      - '--cpu'
      - '1'
      - '--timeout'
      - '300'
      - '--max-instances'
      - '100'
      - '--min-instances'
      - '1'
      - '--set-env-vars'
      - 'GEMINI_API_KEY=${_GEMINI_API_KEY},PORT=8080,RUST_LOG=info'
    env:
      - 'CLOUDSDK_RUN_REGION=${_DEPLOY_REGION}'
    id: 'deploy'

images:
  - '${_AR_HOSTNAME}/${_AR_PROJECT_ID}/${_AR_REPOSITORY}/agent-samwise:latest'
  - '${_AR_HOSTNAME}/${_AR_PROJECT_ID}/${_AR_REPOSITORY}/agent-samwise:$COMMIT_SHA'

options:
  machineType: 'N1_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _AR_HOSTNAME: 'europe-west1-docker.pkg.dev'
  _AR_PROJECT_ID: 'gaiinapp'
  _AR_REPOSITORY: 'cloud-run-source-deploy'
  _SERVICE_NAME: 'agent-samwise'
  _DEPLOY_REGION: 'europe-west1'
  _PLATFORM: 'managed'
  _GEMINI_API_KEY: ''

tags:
  - 'agent-samwise'
  - 'cloud-run'
  - 'rust'
  - 'europe-west1'

timeout: '1800s'
